version: '1'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: 
      - ./env
    ports:
      - 5432:5432
    volumes:
      - db/postgres:/var/lib/postgres

  mongo:
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - db/mongo:/var/lib/mongo

  app:
    depends_on:
      - mongo
      - postgres
    
    restart: unless-stopped
    env_file:
      - ./env

volumes:
  db:


